/*
 * MOTORS_Configurations.h
 *
 *  Created on: Jul 21, 2023
 *      Author: Hesha
 */

#ifndef INCLUDE_HAL_MOTORS_MOTORS_CONFIGURATIONS_H_
#define INCLUDE_HAL_MOTORS_MOTORS_CONFIGURATIONS_H_

#define LEFTMOTORS_PIN0			PIN2
#define LEFTMOTORS_PIN1			PIN3
#define RIGHTMOTORS_PIN0		PIN0
#define RIGHTMOTORS_PIN1		PIN1
#define MOTORS_PORT				PORTA



#endif /* INCLUDE_HAL_MOTORS_MOTORS_CONFIGURATIONS_H_ */
