/*
 * ULTRASONIC_private.h
 *
 *  Created on: Jul 21, 2023
 *      Author: Hesha
 */

#ifndef INCLUDE_HAL_ULTRASONIC_ULTRASONIC_PRIVATE_H_
#define INCLUDE_HAL_ULTRASONIC_ULTRASONIC_PRIVATE_H_



#endif /* INCLUDE_HAL_ULTRASONIC_ULTRASONIC_PRIVATE_H_ */
