/*
 * ULTRASONIC_Configurations.h
 *
 *  Created on: Jul 21, 2023
 *      Author: Hesha
 */

#ifndef INCLUDE_HAL_ULTRASONIC_ULTRASONIC_CONFIGURATIONS_H_
#define INCLUDE_HAL_ULTRASONIC_ULTRASONIC_CONFIGURATIONS_H_

#define ULTRASONIC_TRIG_PIN		PIN5
#define ULTRASONIC_PORT			PORTD



#endif /* INCLUDE_HAL_ULTRASONIC_ULTRASONIC_CONFIGURATIONS_H_ */
